<Project Sdk="Fahrenheit.Sdk/1.0.0-alpha12">
    <!--
    Welcome to an example .csproj file for a Fahrenheit module!

    When in doubt, you can consult this to see what options need to be set and why.

    Assume that the order in which these groups appear is intentional. When preparing your own project, use the same order.
    -->

    <!-- ASSEMBLY BASIC PROPERTIES -->
	<PropertyGroup>
		<Version>0.5.2-alpha</Version>
	</PropertyGroup>

    <!-- ASSEMBLY ADDITIONAL PROPERTIES -->
    <PropertyGroup>
        <AssemblyName>custom-character</AssemblyName>
        <AssemblyTitle>Custom Character Mod</AssemblyTitle>
        <Product>Custom Character Mod</Product>
		<Authors>Rurusachi</Authors>
		<RepositoryType>git</RepositoryType>
		<RepositoryUrl>https://github.com/rurusachi/custom-character.git</RepositoryUrl>
		<FhManifestFlags>NONE</FhManifestFlags>
    </PropertyGroup>

    <!-- SHARED FILE LINKS -->
    <ItemGroup>
        <None Include="$(SolutionDir).editorconfig" Link=".editorconfig" />
    </ItemGroup>
</Project>
